define('footer.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data,blockParams,depths) {
    var alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3=container.escapeExpression;

  return " <script defer src=\"https://use.fontawesome.com/releases/v5.0.8/js/all.js\"></script><style> .fw{\n	color:white;\n}\n\n.transition {\n  -webkit-transform: scale(1.5);\n  -moz-transform: scale(1.5);\n  -o-transform: scale(1.5);\n  transform: scale(1.5);\n} </style><script> $(document).ready(function(){\n\n	$('.expa').hover(function(){\n	      $(this).addClass('transition');\n	},function(){\n	    $(this).removeClass('transition');\n	});\n\n}); </script><div class=\"container-fluid\" style=\"background-color:#343741; padding-bottom:28px;\"><div class=\"row\" style=\"padding-top:10px; text-align:center; \"><div class=\"col-lg-2 col-md-2 col-sm-2 text-center\" style=\"background-color:; padding-bottom:-15px; padding-top:15px;\"><div class=\"expa\"><a href=\"/NFL\" ><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/Icons/Leagues/NFL.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" height=\"46\" width=\"100\" /></a></div></div><div class=\"col-lg-2 col-md-2 col-sm-2 text-center\" style=\"background-color:; padding-bottom:-15px; padding-top:15px;\"><div class=\"expa\"><a href=\"/MLB\" ><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/Icons/Leagues/MLB.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" height=\"46\" width=\"100\"  /></a></div></div><div class=\"col-lg-2 col-md-2 col-sm-2 text-center\" style=\"background-color:; padding-bottom:-15px; padding-top:15px;\"><div class=\"expa\"><a href=\"/NCAA\" ><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/Icons/Leagues/NCAA.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" height=\"46\" width=\"100\" /></a></div></div><div class=\"col-lg-2 col-md-2 col-sm-2 text-center\" style=\"background-color:; padding-bottom:-15px; padding-top:15px;\"><div class=\"expa\"><a href=\"/NBA\" ><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/Icons/Leagues/NBA.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" height=\"46\" width=\"100\"  /></a></div></div><div class=\"col-lg-2 col-md-2 col-sm-2 text-center\" style=\"background-color:; padding-bottom:-15px; padding-top:15px;\"><div class=\"expa\"><a href=\"/NHL\" ><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/Icons/Leagues/NHL.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" height=\"46\" width=\"100\"  /></a></div></div><div class=\"col-lg-2 col-md-2 col-sm-2 text-center\" style=\"background-color:; padding-bottom:-15px; padding-top:15px;\"><div class=\"expa\"><a href=\"/margaritaville\" ><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/Icons/Leagues/MARGARITAVILLE.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" height=\"46\" width=\"100\"  /></a></div></div></div></div><div data-view=\"Global.BackToTop\"></div><div class=\"footer-content\" style=\"\"><div id=\"banner-footer\" class=\"content-banner banner-footer\" data-cms-area=\"global_banner_footer\" data-cms-area-filters=\"global\"></div><div class=\"row\" style=\"padding-top:10px; text-align:center; \"><div class=\"col-lg-3 col-md-6 col-sm-6 text-center\" style=\"background-color:; padding-bottom:-15px; padding-bottom:15px;\"><div class=\"\" ><h3 style=\"padding-top:10px; padding-bottom:10px; color:white;text-align:left;\">SUPPORT</h3><ul class=\"text-faded fw\" style=\"text-align:left; \"><li class=\"fr bpoints\"><p class=\"fw\">Download High-Res Images</p></li><li class=\"fr bpoints\"><p class=\"fw\">New Products Ideas</p></li><li class=\"fr bpoints\"><p class=\"fw\">Sell Sheets</p></li><li class=\"fr bpoints\"><p class=\"fw\">Vendor Portal</p></li></ul></div></div><div class=\"col-lg-3 col-md-6 col-sm-6 text-center\" style=\"background-color:; padding-bottom:-15px; padding-bottom:15px;\"><div class=\"\"><h3 style=\"padding-top:10px; padding-bottom:10px; color:white; text-align:left;\">PRODUCTS</h3><ul class=\"text-faded fw\" style=\"text-align:left; \"><li class=\"fr bpoints\"><p class=\"fw\">Hot Market</p></li><li class=\"fr bpoints\"><p class=\"fw\">New Products</p></li><li class=\"fr bpoints\"><p class=\"fw\">Personalization</p></li><li class=\"fr bpoints\"><p class=\"fw\">Pet</p></li></ul></div></div><div class=\"col-lg-3 col-md-6 col-sm-6 text-center\" style=\"background-color:; padding-bottom:-15px; padding-bottom:15px;\"><div class=\"\"><h3 style=\"padding-top:10px; padding-bottom:10px; color:white; text-align:left;\">COMPANY</h3><ul class=\"text-faded fw\" style=\"text-align:left; \"><li class=\"fr bpoints\"><p class=\"fw\">About Us</p></li><li class=\"fr bpoints\"><p class=\"fw\">Careers</p></li><li class=\"fr bpoints\"><p class=\"fw\">Contact Us</p></li></ul></div></div><div class=\"col-lg-3 col-md-6 col-sm-6 text-center\" style=\"background-color:; padding-bottom:-15px; padding-bottom:15px;\"><div class=\"\"><h3 style=\"padding-top:10px; padding-bottom:10px;color:white; text-align:left;\">SOCIAL MEDIA</h3><div style=\"text-align:left;\"><a href=\"https://www.facebook.com/RicoIndustriesInc\" target=\"_blank\" class=\"fw\" ><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/SocialMedia/facebookw.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" width=\"42\" height=\"42\"/></a><a href=\"https://www.facebook.com/RicoIndustriesInc\" target=\"_blank\" class=\"fw\" style=\"padding-left:5px;text-align:left;\"><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/SocialMedia/twitterw.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" width=\"42\" height=\"42\"/></a><a href=\"https://www.facebook.com/RicoIndustriesInc\" target=\"_blank\" class=\"fw\" style=\"padding-left:5px; text-align:left;\"><img src=\""
    + alias3((compilerNameLookup(helpers,"getThemeAssetsPath") || (depth0 && compilerNameLookup(depth0,"getThemeAssetsPath")) || alias2).call(alias1,(compilerNameLookup(helpers,"resizeImage") || (depth0 && compilerNameLookup(depth0,"resizeImage")) || alias2).call(alias1,"img/SocialMedia/linkedinw.png",(depths[1] != null ? compilerNameLookup(depths[1],"imageHomeSize") : depths[1]),{"name":"resizeImage","hash":{},"data":data}),{"name":"getThemeAssetsPath","hash":{},"data":data}))
    + "\" alt=\"\" width=\"42\" height=\"42\"/></a></div></div></div></div></div><div class=\"col-lg-12 col-md-12 col-sm-12\" style=\"background-color:#343741;padding-top:5px;padding-bottom:6px;\"><div class=\"footer-copyright py-3 text-center \" style=\"\" id=\"privacyandterms\"> © 2018 Rico Industries, Inc. All Rights Reserved. <a style=\"color:white; font-weight: normal;\" href=\"http://www.ricoinc.com/\"> Privacy Policy </a><span> | </span><a style=\"color:white; font-weight: normal;\" href=\"http://www.ricoinc.com/\"> Terms and Conditions </a></div></div>  ";
},"useData":true,"useDepths":true}); template.Name = 'footer'; return template;});