define('product_line_sku2.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, alias1=container.lambda, alias2=container.escapeExpression;

  return " <script> $(document).ready(function(){\n\n$(\"a#url1img\").attr(\"href\", $(\"p#url1imgp\").text());\n$(\"a#url2img\").attr(\"href\", $(\"p#url2imgp\").text());\nvar counter = 0;\n$(\"div#morecontainer a.spantext\").each(function() {\n\n	var text = $(this).text();\n	counter++;\n	if (text == '') {\n	$(\".span\"+counter).remove();\n	}\n	});\n\nvar imgurl2 = $(\"p#url1imgp\").text();\nvar urlnew2 = imgurl2.substr(0, imgurl2.indexOf('_main'));\nvar url2 = urlnew2+\".jpg\";\n//$(\"#url3img\").text(url);\n$(\"#url3img\").attr(\"href\", url2);\n//$(\"#url3img\").text(url2);\n\n});\n/*$('#downloadinfoact').on('click', function() { ohSnap('For the privacy of the Internet, you can no longer download a direct image, to download the image you must click on \"Download image button\"> right click> save image as.', {color:'yellow'})});*/ </script><div class=\"product-line-sku-container\" id=\"morecontainer\" ><div><span class=\"product-line-sku-value\" itemprop=\"sku\"><a id=\"url3img\" href=\"\" target=\"_blank\">High Resolution Image</a></span></div><div style=\"padding-top:5px;\" class=\"span1\"><span class=\"product-line-sku-value span1\" itemprop=\"sku\"> Full Title: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem_store_header_2") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span2\"><span class=\"product-line-sku-value span2\" itemprop=\"sku\"><p id=\"url1imgp\" style=\"display:none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem_image1") : stack1), depth0))
    + "</p><a class=\"spantext\" id=\"url1img\" href=\"\" target=\"_blank\">Main Image</a></span></div><div style=\"padding-top:5px;\" class=\"span3\"><span class=\"product-line-sku-value span3\" itemprop=\"sku\"><p id=\"url2imgp\" style=\"display:none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem_thumbnail1") : stack1), depth0))
    + "</p><a class=\"spantext\" id=\"url2img\" href=\"\" target=\"_blank\">Thumbnail Image</a></span></div><div style=\"padding-top:5px;\" class=\"span4\"><span class=\"product-line-sku-value span4\" itemprop=\"sku\"> Sport: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem_rico_sport") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span5\"><span class=\"product-line-sku-value span5\" itemprop=\"sku\"> League: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem1") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span6\"><span class=\"product-line-sku-value span6\" itemprop=\"sku\"> Team: <a id=\"itemteam\" class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem2") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span7\"><span class=\"product-line-sku-value span7\" itemprop=\"sku\"> Region: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem_store_team_region") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span8\"><span class=\"product-line-sku-value span8\" itemprop=\"sku\"> State: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem_store_team_state") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span9\"><span class=\"product-line-sku-value span9\" itemprop=\"sku\"> Brand: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitemstore_item_brand") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span10\"><span class=\"product-line-sku-value span10\" itemprop=\"sku\"> Product Type: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem_prodtype") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span11\"><span class=\"product-line-sku-value span11\" itemprop=\"sku\"> Order Minimum: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"minimumquantity") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span12\"><span class=\"product-line-sku-value span12\" itemprop=\"sku\"> Manufacturer Part Number: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem_store_manufacturer_part_no") : stack1), depth0))
    + "</a></span></div><div style=\"padding-top:5px;\" class=\"span13\"><span class=\"product-line-sku-value span13\" itemprop=\"sku\"> Model: <a class=\"spantext\" style=\"text-decoration:none; color:inherit; pointer-events: none;\">"
    + alias2(alias1(((stack1 = ((stack1 = (depth0 != null ? compilerNameLookup(depth0,"model") : depth0)) != null ? compilerNameLookup(stack1,"item") : stack1)) != null ? compilerNameLookup(stack1,"custitem_store_model_number") : stack1), depth0))
    + "</a></span></div></div>  ";
},"useData":true}); template.Name = 'product_line_sku2'; return template;});